export default {
  AuthState: {
    user: null,
    isAuthenticated: false,
  },
  addedToWaitList: false,
  creatorsDBCount: '3M',
  CRMSidebarOpen: true,
  ContactSidebarOpen: false,
  crmRecords: [],
  showImportProgress: false,
  importProgressSingleCount: 0,
  tooltipsEnabled: false,
  crmEventsRegistered: false,
  isExtension: false,
  extensionQuery: null,
  theme: 'light',
  chromeExtensionInstalled: false,
  jovieVersion: '0.0.9',
  crmPage: {
    stages: [],
    networks: [],
    showCustomFieldsModal: false,
    currentCustomField: null,
    currentContact: null,
    currentRow: null,
    currentColumn: null,
    currentCell: {
      row: 0,
      column: 0,
    },
  },
  currentlyDraggedContact: null,
  overviewList: null,
};
